openapi: 3.1.0
info:
  title: BPCC SCIM-Compliant User Provisioning API
  version: 1.0.0
  description: 'Introduction


    The Bright Pattern Contact Center (BPCC) SCIM-Compliant User Provisioning API implements the System
    for Cross-domain Identity Management (SCIM) open standard to simplify user provisioning in Bright
    Pattern cloud contact center environments via a third-party system. SCIM communicates user identity
    data between identity providers and service providers requiring user identity information.


    With the BPCC SCIM-Compliant User Provisioning API, you can do the following:


    Create new users and define their general (i.e., not contact-center specific) attributes (e.g., names,
    contact information, photo, etc.)


    Get user information by ID or username


    Update general user properties including username


    Delete existing users


    This document specifies the corresponding REST API methods, with example requests and responses. You
    can load this API into the Postman API Development Environment to interact with the API with your
    own access tokens.


    For the complete SCIM description, see RFC 7643 and RFC 7644.


    Prerequisites


    To use this API, users will need the following:


    A configured integration account


    A user account that will be used for API authentication with the following privileges:

    Manage users


    Manage all teams


    Notes


    In addition to the prerequisites, please note the following.


    Team Assignment


    Any user created via the SCIM-Compliant User Provisioning API will be assigned to the team specified
    as the Default team in the integration account.


    Role Assignment


    User roles can be specified via the API. If no roles are specified, a newly created user will receive
    the role defined in Assign this role to newly created users.


    Username Changes


    Note that in order for usernames to be changed, service providers must allow this feature for your
    contact center. For more information, see the Contact Center Administrator Guide, section Users.


    Passwords


    Setting a password for a newly created user is optional. Empty passwords can be used, for example,
    if your contact center users log in via single sign-on (SSO). If the password is not specified, it
    will be autogenerated. If the password is specified, it must meet all of the password complexity requriements
    defined by your service provider.


    Softphones


    The newly created user accounts receive automatically assigned/created softphone numbers as usual.


    Microsoft Azure


    The BPCC SCIM-Compliant User Provisioning API is compatible with the SCIM schema used by Microsoft
    Azure.'
  contact:
    name: Bright Pattern
    url: https://www.brightpattern.com/contact/
  x-origin:
  - format: postman
    url: https://documenter.getpostman.com/view/8336025/SVYwJbLw
    version: '2.1'
  x-evidence:
    fetched: '2026-08-08'
    source: https://documenter.gw.postman.com/api/collections/8336025/SVYwJbLw?segregateAuth=true&versionTag=latest
    http_status: 200
    method: derived-from-published-postman-collection
    note: Mechanically converted from the Postman collection Bright Pattern publishes as its public API
      reference. No operations, paths, parameters or examples were invented.
servers:
- url: https://{tenant_url}
  description: Bright Pattern is multi-tenant; the base host is the customer contact-center tenant domain.
  variables:
    tenant_url:
      default: example.brightpattern.com
      description: Your Bright Pattern Contact Center tenant hostname.
tags:
- name: Authentication
  description: 'The OAuth 2.0 Client Credentials Grant is used to authenticate clients of this API. The
    authenticated user is checked for having appropriate privileges to perform the requested operation.
    The complete list of privileges can be found here. Privileges are assigned to users via one or more
    roles.


    To obtain an access token:


    Login to the Contact Center Administrator application.


    Navigate to the Users page. Select or create a user with privileges corresponding to the tasks you
    wish to perform via the BPCC SCIM-Compliant User Provisioning API.


    Click the Generate button to generate an API secret key. Copy the generated key and note the username
    for the next steps.


    Use the Get Access Token method to obtain an access token. Set the client_id to the username and client_secret
    to the generated API secret key.


    Use the value of access_token returned in the response to set the Authorization: Bearer [access token]
    header of each subsequent request made via the BPCC SCIM-Compliant User Provisioning API.'
- name: Users
  description: 'With the https://<tenant_url>/configapi/v2/scim/users endpoint, you

    can do the following:


    Create new users and define most of their attributes


    Get user information by ID or username


    Update user information including username


    Delete existing users


    Below is a description of user attributes that can be accessed via this API. All attributes are strings
    unless otherwise noted. All attributes are required unless otherwise noted. Note: If a certain SCIM
    field is not listed, it is not supported by BPCC.


    SCIM

    BPCC Mapping

    Required

    Read/Write

    Notes


    active

    Disabled

    No

    Read/write

    Note the inversion: active = true translates to Disabled = false and vice versa


    addresses/Country

    Country

    No

    Read/write

    See Notes for "addresses/primary"


    addresses/locality

    City

    No

    Read/write

    See Notes for "addresses/primary"


    addresses/primary

    See Notes


    SCIM allows for the specification of multiple physical addresses. If the array contains more than
    one address, BPCC will take the above attributes from the one that has the  "primary" attribute set
    to "true". If none of the addresses have the "primary" attribute, BPCC will take the above attributes
    from the first address in the array.


    addresses/region

    State/Province

    No

    Read/write

    See Notes for "addresses/primary"


    emails/primary

    See Notes


    SCIM allows for the specification of multiple email addresses. If the array contains more than one
    email address, BPCC will take the one that has the "primary" attribute set to "true". If none of the
    addresses have the "primary" attribute, BPCC will take the first email address in the array.


    emails/value

    Email address

    Yes

    Read/write

    See Notes for "email/primary"


    externalId

    See "userName"

    No

    Read only

    This attribute is ignored in requests; it always sets an empty string in responses.


    id

    UUID of the user object in the Configuration Database

    No

    Read only

    Appears in responses only


    meta/location

    Equal to the "Location" header of a newly created resource

    No

    Read only

    https://tools.ietf.org/html/rfc7231#section-3.1.4.2


    meta/resourceType

    See Notes

    No

    Read only

    Appears in responses only; always set to "USER"


    name/familyName

    Last name

    No

    Read/write

    Must be specified in the Create User method


    name/givenName

    First name

    No

    Read/write

    Must be specified in the Create User method


    nickName

    Chat nickname

    No

    Read/write


    password

    Password

    No

    Write only

    Setting a password for a newly created user is optional. Empty passwords can be used, for example,
    if your contact center users log in via single sign-on (SSO). If the password is not specified, it
    will be autogenerated. If the password is specified, it must meet all of the password complexity requriements
    defined by your service provider. The password will not be returned in any SCIM responses.


    phoneNumbers/type

    See Notes


    -   When set to "extension", the "phoneNumbers/value" attribute maps to "Phone extension"; if the
    specified number is assigned to another user, the Create/Update request will return an error.


    -   When set to "default", the "phon…'
paths:
  /configapi/v2/oauth/token:
    post:
      operationId: getAccessToken
      summary: Get Access Token
      description: 'Returns an access token that will be used to authenticate each

        subsequent request made via this API.'
      tags:
      - Authentication
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  description: Username of a Bright Pattern user authorized to manage users and manage
                    all teams
                client_secret:
                  type: string
                  description: API secret key generated for the above user
                scope:
                  type: string
                  description: Your contact center URL (e.g., yourcompany.brightpattern.com)
                grant_type:
                  type: string
                  description: Grant type; must be set to client_credentials
            example:
              client_id: ''
              client_secret: ''
              scope: ''
              grant_type: ''
      responses:
        '200':
          description: Get Access Token
          content:
            application/json:
              example:
                access_token: 5EIBcIV2zmmlMm1ArGYYnEYFzePHJtXs0dE41LTfMiRH8y607e5cTIEunZS2EvQi
                token_type: Bearer
                expires_in: '3600'
                scope: hgsandbox.brightpattern.com
      security: []
  /configapi/v2/scim/users:
    post:
      operationId: createUser
      summary: Create User
      description: This method creates a new user in your contact center configuration.
      tags:
      - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              schemas:
              - urn:ietf:params:scim:schemas:core:2.0:User
              userName: bjensen@example.com
              name:
                familyName: Jensen
                givenName: Barbara
              nickName: Babs
              emails:
              - value: bjensen@example.com
              addresses:
              - locality: Hollywood
                region: CA
                country: US
              phoneNumbers:
              - value: 555-555-5555
                type: work
              - value: 555-555-4444
                type: mobile
              photos:
              - value: https://www.brightpattern.com/wp-content/uploads/2017/09/bright-pattern-logo-mini-with-text-30.png
                type: photo
              title: TSR Level 3
              timezone: America/Los_Angeles
              active: true
      responses:
        '201':
          description: Create user
          content:
            application/json:
              example:
                schemas:
                - urn:ietf:params:scim:schemas:core:2.0:User
                id: 65625121-E207-4AA6-9C9D-317EE309FFBA
                externalId: ''
                meta:
                  resourceType: USER
                  location: http://localhost:8080/configapi/v2/scim/users/65625121-E207-4AA6-9C9D-317EE309FFBA
                userName: bjensen@example.com
                nickName: Babs
                name:
                  familyName: Jensen
                  givenName: Barbara
                title: TSR Level 3
                timezone: America/Los_Angeles
                active: true
                emails:
                - value: bjensen@example.com
                  primary: true
                phoneNumbers:
                - type: work
                  value: 555-555-5555
                - type: mobile
                  value: 555-555-4444
                - type: extension
                  value: '2083'
                addresses:
                - locality: Hollywood
                  country: US
                roles:
                - value: System Administrator
      security:
      - bearerAuth: []
    get:
      operationId: getUserByUsername
      summary: Get User by userName
      description: This method returns detailed configuration information about an existing user via the
        userName filter.
      tags:
      - Users
      parameters:
      - name: filter
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Get User by userName
          content:
            application/scim+json:
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:ListResponse
                totalResults: 1
                Resources:
                - schemas:
                  - urn:ietf:params:scim:schemas:core:2.0:User
                  id: 1F148A86-BF13-4478-A102-F11A8B664FF8
                  meta:
                    resourceType: USER
                    created: 06-03-2020T07:46:33
                    location: http://yourcompany.brightpattern.com/configapi/v2/scim/users/1F148A86-BF13-4478-A102-F11A8B664FF8
                  userName: carlos.clapper
                  name:
                    familyName: Clapper
                    givenName: Carlos
                  active: true
                  emails:
                  - value: carlos.clapper@contactcenter.office
                    primary: true
                  phoneNumbers:
                  - type: extension
                    value: '2025'
                  addresses:
                  - {}
                  roles:
                  - Agent
      security:
      - bearerAuth: []
  /configapi/v2/scim/users/{id}:
    get:
      operationId: getUserById
      summary: Get User by ID
      description: This method returns detailed configuration information about an existing user via the
        user’s ID.
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get User by ID
          content:
            application/json:
              example:
                schemas:
                - urn:ietf:params:scim:schemas:core:2.0:User
                id: 5974D6AE-66BD-4B2A-A9D6-1AEADD18F669
                meta:
                  resourceType: USER
                  created: 06-03-2020T10:04:30
                  lastModified: 06-03-2020T10:35:28
                  location: http://yourcompany.brightpattern.com/configapi/v2/scim/users/5974D6AE-66BD-4B2A-A9D6-1AEADD18F669
                userName: elizabeth
                name:
                  familyName: Smith
                  givenName: Liza
                active: true
                emails:
                - value: liza@smith.com
                  primary: true
                phoneNumbers:
                - type: extension
                  value: '2064'
                addresses:
                - {}
                roles:
                - System Administrator
                - Campaign Administrator
                - Supervisor
                - Quality Evaluator
                - Quality Evaluator Admin
                - Security Administrator
                - Campaign Operator
                - Service Administrator
                - Reviewer
                - Manager
                - Agent
      security:
      - bearerAuth: []
    put:
      operationId: replaceUserProperties
      summary: Replace User Properties (by replacing all existing attributes with a specified set of replacement
        attributes)
      description: 'Replaces all attributes of an existing user with a specified set of replacement attributes.
        Note that in accordance with RFC7644, the PUT method updates users by replacing all of their current
        attributes with the ones specified in the body of the method.


        Note also that in order for usernames to be changed, service providers must allow this feature
        for your contact center. For more information, see the Contact Center Administrator Guide, section
        Users.'
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              schemas:
              - urn:ietf:params:scim:schemas:core:2.0:User
              userName: bjinsin
              name:
                familyName: Jinsin
                givenName: Borbora
              nickName: Bobs
              emails:
              - value: bjinsin@example.com
              addresses:
              - locality: Hollywood
                region: CA
                country: US
              phoneNumbers:
              - value: 555-555-5555
                type: work
              - value: 888-888-8888
                type: mobile
              title: TSR Level 3
              timezone: America/Los_Angeles
              active: true
      responses:
        '200':
          description: Replace User
          content:
            application/json:
              example:
                schemas:
                - urn:ietf:params:scim:schemas:core:2.0:User
                id: 7D6A5564-2104-442F-82DA-D55B6D7CFAE9
                meta:
                  resourceType: USER
                  created: 09-03-2020T05:58:01
                  lastModified: 09-03-2020T09:21:44
                  location: http://mordor.brightpattern.com/configapi/v2/scim/users/7D6A5564-2104-442F-82DA-D55B6D7CFAE9
                userName: bjinsin
                nickName: Bobs
                name:
                  familyName: Jinsin
                  givenName: Borbora
                title: TSR Level 3
                timezone: America/Los_Angeles
                active: true
                emails:
                - value: bjinsin@example.com
                  primary: true
                phoneNumbers:
                - type: work
                  value: 555-555-5555
                - type: mobile
                  value: 888-888-8888
                - type: extension
                  value: '2065'
                addresses:
                - locality: Hollywood
                  region: CA
                  country: US
                roles: []
      security:
      - bearerAuth: []
    delete:
      operationId: deleteUser
      summary: Delete User
      description: Deletes an existing user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Delete User
      security:
      - bearerAuth: []
    patch:
      operationId: updateUser
      summary: Update User (updates only the properties indicated in the specified set)
      description: 'Updates attributes of an existing user. Note that in accordance with RFC7644, the
        PATCH method modifies a user with a set of client-specified changes (partial update).


        Note also that in order for usernames to be changed, service providers must allow this feature
        for your contact center. For more information, see the Contact Center Administrator Guide, section
        Users.'
      tags:
      - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              schemas:
              - urn:ietf:params:scim:api:messages:2.0:PatchOp
              Operations:
              - op: replace
                path: active
                value: false
      responses:
        '200':
          description: Update User (updates only the properties indicated in the specified set)
          content:
            application/scim+json:
              example:
                schemas:
                - urn:ietf:params:scim:schemas:core:2.0:User
                id: 6BE15F09-BF39-4E20-AB31-A9355CBC01FC
                meta:
                  resourceType: USER
                  lastModified: '2022-04-01T01:07:15'
                  location: http://alexei-maintenance.pl.bugfocus.com/configapi/v2/scim/users/6BE15F09-BF39-4E20-AB31-A9355CBC01FC
                userName: carlos.clapper
                name:
                  familyName: Clapper
                  givenName: Carlos
                timezone: America/Los_Angeles
                active: false
                emails:
                - value: carlos.clapper@servicepattern.sb.office
                  primary: true
                phoneNumbers:
                - type: extension
                  value: '2025'
                addresses: []
                roles:
                - value: System Administrator
                - value: Agent
                groups:
                - value: 84FB1AD4-1B27-4CFA-A1E0-B8A972F3EFA7
                  display: CSIM Support
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      x-normalized-from: /configapi/v2/scim/users/6BE15F09-BF39-4E20-AB31-A9355CBC01FC (the published
        collection hard-codes an example user id in the URL)
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: 'OAuth 2.0 access token issued by the Bright Pattern token endpoint, sent as `Authorization:
        Bearer <token>`.'
    oauth2ClientCredentials:
      type: oauth2
      description: OAuth 2.0 client-credentials grant against the Bright Pattern tenant token endpoint.
      flows:
        clientCredentials:
          tokenUrl: https://{tenant_url}/configapi/v2/oauth/token
          scopes: {}
security:
- bearerAuth: []
